# Generated by Django 4.2.4 on 2023-08-28 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarVW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default='VAG', editable=False, max_length=250, verbose_name='Brand')),
                ('date_to_add', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DieselEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_fuel_sytem', models.CharField(choices=[('TDI PD', 'PumpDuse system with turbocharger'), ('Diesel PD', 'PumpDuse system without turbocharger'), ('TDI CR', 'Common Rail system with turbocharger')], max_length=250, verbose_name='Type of fuel system')),
                ('image', models.ImageField(upload_to='storage', verbose_name='выбрать файл для загрузки')),
                ('date_to_add', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelOfCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_of_car', models.CharField(choices=[('G', 'golf'), ('S', 'scirocco')], max_length=250)),
                ('image', models.ImageField(upload_to='storage', verbose_name='выбрать файл для загрузки')),
                ('date_to_add', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carvw')),
            ],
        ),
        migrations.AddField(
            model_name='carvw',
            name='diesel_engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dieselengine'),
        ),
    ]
