# Generated by Django 4.2.4 on 2023-08-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarVW',
            new_name='VWCar',
        ),
    ]
