# Generated by Django 4.2.4 on 2023-09-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_carvw_vwcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieselengine',
            name='image',
            field=models.ImageField(blank=True, upload_to='storage', verbose_name='выбрать файл для загрузки'),
        ),
        migrations.AlterField(
            model_name='modelofcar',
            name='image',
            field=models.ImageField(blank=True, upload_to='storage', verbose_name='выбрать файл для загрузки'),
        ),
        migrations.AlterField(
            model_name='modelofcar',
            name='model_of_car',
            field=models.CharField(choices=[('Golf', 'golf'), ('Scirocco', 'scirocco')], max_length=250),
        ),
    ]
